spring:
  application:
    name: exchange-gateway
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        - id: exchange-user-route
          uri: lb://exchange-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: exchange-auth-route
          uri: lb://exchange-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: exchange-position-route
          uri: lb://exchange-position
          predicates:
            - Path=/position/**
          filters:
            - StripPrefix=1
        - id: exchange-market-route
          uri: lb://exchange-market-data
          predicates:
            - Path=/market/**
          filters:
            - StripPrefix=1

open:
  vincentf13:
    id-generator:
      snowflake:
        worker-id: 3
