spring:
  application:
    name: exchange-gateway
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        - id: exchange-user-route
          uri: lb://exchange-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: exchange-auth-route
          uri: lb://exchange-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: exchange-position-route
          uri: lb://exchange-position
          predicates:
            - Path=/position/**
          filters:
            - StripPrefix=1
        - id: exchange-market-route
          uri: lb://exchange-market
          predicates:
            - Path=/market/**
          filters:
            - StripPrefix=1
        - id: exchange-account-route
          uri: lb://exchange-account
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: exchange-admin-route
          uri: lb://exchange-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: exchange-order-route
          uri: lb://exchange-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: exchange-risk-route
          uri: lb://exchange-risk
          predicates:
            - Path=/risk/**
          filters:
            - StripPrefix=1
        - id: exchange-matching-route
          uri: lb://exchange-matching
          predicates:
            - Path=/matching/**
          filters:
            - StripPrefix=1

open:
  vincentf13:
    id-generator:
      snowflake:
        worker-id: 3
    pending-task:
      rescue:
        enabled: true
