apiVersion: v1
kind: Service
metadata:
  name: infra-kafka-connect
  labels:
    app: infra-kafka-connect
spec:
  selector:
    app: infra-kafka-connect
  ports:
    - name: rest
      protocol: TCP
      port: 8083
      targetPort: 8083
