apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: infra-kafka-connect-local
  labels:
    app: infra-kafka-connect
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
