spring:
  application:
    name: exchange-order
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

mybatis:
  type-aliases-package: open.vincentf13.exchange.order.infra.persistence.po

open:
  vincentf13:
    id-generator:
      snowflake:
        worker-id: 3
    mybatis:
      mapper-base-packages: open.vincentf13.exchange.order.infra.persistence.mapper
    exchange:
      order:
        position:
          consumer-group: exchange-order-position
        ledger:
          consumer-group: exchange-order-ledger
        risk:
          consumer-group: exchange-order-risk
        matching:
          consumer-group: exchange-order-matching
