spring:
  application:
    name: exchange-account
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

mybatis:
  type-aliases-package: open.vincentf13.exchange.account.infra.persistence.po

open:
  vincentf13:
    id-generator:
      snowflake:
        worker-id: 7
    mybatis:
      mapper-base-packages: open.vincentf13.exchange.account.infra.persistence.mapper
    retry-task:
      rescue:
        enabled: false
