apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-template
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /service-template/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-template
                port:
                  number: 8080
          - path: /service-test/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-test
                port:
                  number: 8080
          - path: /exchange/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: exchange-gateway
                port:
                  number: 8080
