apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-template
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /service-template(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-template
                port:
                  number: 8080
