spring:
  application:
    name: exchange-risk
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

mybatis:
  type-aliases-package: open.vincentf13.exchange.risk.infra.persistence.po
  mapper-locations: classpath*:mapper/*.xml

open:
  vincentf13:
    id-generator:
      snowflake:
        worker-id: 9
    mybatis:
      mapper-base-packages: open.vincentf13.exchange.risk.infra.persistence.mapper

exchange:
  risk:
    mark-price-cache:
      ttl: 5s
    precheck:
      maintenance-buffer: 0.001
