spring:
  application:
    name: exchange-market
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

mybatis:
  type-aliases-package: open.vincentf13.exchange.market.infra.persistence.po

open:
  vincentf13:
    id-generator:
      snowflake:
        worker-id: 8
    mybatis:
      mapper-base-packages: open.vincentf13.exchange.market.infra.persistence.mapper
    exchange:
      market:
        orderbook:
          consumer-group: exchange-market-orderbook
        trade:
          consumer-group: exchange-market-trade
    pending-task:
      rescue:
        enabled: false
