apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-test
  labels:
    app: service-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-test
  template:
    metadata:
      labels:
        app: service-test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: service-test
          image:  victorf13/service-test:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"           # 自動擴容的必要條件，需配置
