spring:
  application:
    name: exchange-auth
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

mybatis:
  type-aliases-package: open.vincentf13.exchange.auth.infra.persistence.po

open:
  vincentf13:
    id-generator:
      snowflake:
        worker-id: 1
    mybatis:
      mapper-base-packages: open.vincentf13.exchange.auth.infra.persistence.mapper
    pending-task:
      rescue:
        enabled: false
