spring:
  application:
    name: exchange-user
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

#logging:
#  level:
#    open.vincentf13.exchange.user: INFO

mybatis:
  type-aliases-package: open.vincentf13.exchange.user.infra.persistence.po

open:
  vincentf13:
    id-generator:
      snowflake:
        worker-id: 2
    mybatis:
      mapper-base-packages: open.vincentf13.exchange.user.infra.persistence.mapper
    pending-task:
      rescue:
        enabled: false
